version: '3.8'
services:
  database:
    container_name: Postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mailcatcher:
    image: dockage/mailcatcher:latest
    container_name: Mailer
    ports:
    - "1080:1080"
    - "1025:1025"